# Generated by Django 5.1.2 on 2024-11-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_collation='utf8mb4_spanish_ci', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_collation='utf8mb4_spanish_ci\t', null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
    ]
